# Generated by Django 2.1.7 on 2019-04-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_entry',
            old_name='log_data',
            new_name='_log_data',
        ),
    ]
